### ISSUE TITLE
Despite my giving inventaire app permission to edit wikidata with my account, the modification is made by Maxlath

### ISSUE THREAD

**Issue by pandark** [inventaire/inventaire#116]
I added the French name of Freakonomics (which is… Freakonomics 😆) using inventaire.io. The app asked me to log in wikidata and give it permissions. I did. Then I checked the page to see what changed…
See https://www.wikidata.org/w/index.php?title=Q1211497&diff=588192954&oldid=586068744

**Comment by maxlath** [comment]
wooh, thanks for spotting that!! There got to be something wrong in the OAuth setup, I will have a look

**Comment by maxlath** [comment]
So the problem doesn't seem to come from the OAuth authorization as I could make an edit from another account than maxlath (my apologies, [I used your oauth tokens to test that on the sandbox](https://www.wikidata.org/w/index.php?title=Q4115189&oldid=589719715) before thinking that I could just create another Wikidata account to test it, I hope that's ok).

Second check: I could locally witness that starting the server [editing from one account](https://www.wikidata.org/w/index.php?title=Q4115189&oldid=589762204), then [editing from another account](https://www.wikidata.org/w/index.php?title=Q4115189&oldid=589762733) was actually resulting as both edit being signed by the first account, this account not necessarly being `Maxlath`: I suspect the issue is coming from `wikidata-edit` caching tokens

**Comment by maxlath** [comment]
[`wikidata-edit` was indeed caching tokens](https://github.com/maxlath/wikidata-edit/commit/7223a67) so after updating to the patched version and restarting the server, it seems to be working!
