### ISSUE TITLE
Prevent scroll on asides bar

### ISSUE THREAD

**Issue by Jitrixis** [inventaire/inventaire#18]
Hi,

Scrolling on asides bar should be prevent, because sometimes it can make some double scrolling probleme or a non desire scroll to the main content.

Cordialy.

[Google Drive Video](https://drive.google.com/file/d/0B2GcDigi53j-eHdJX3NWbl9YaU0/view?usp=sharing)

**Comment by maxlath** [comment]
hi, thanks for reporting it!
Indeed it isn't very nice, especially as the inventory part is empty, but I don't see how to do otherwise for now.
The friends list UI is very much inspired by facebook's one, which seem to have the same problem: when you scroll to the end of the aside, scrolling further triggers the main scrolls. This is less a problem as the main part isn't empty and thus not bumping as in your video

**Comment by maxlath** [comment]
closing it for now as aside scroll bar are an important part of the current UI, can be reopened if an elegant alternatives emerge
