### ISSUE TITLE
Unable to specify a serie (invalid claim entity type: work)

### ISSUE THREAD

**Issue by pdesgarets** [inventaire/inventaire#190]
Hi,
I wanted to update the "Series" property for a book, and I get 400 Error `invalid claim entity type: work` each time I want to set it to Largo Winch (https://inventaire.io/entity/wd:Q727911). It works with a different series (for instance XIII).

Thanks for your help

**Comment by maxlath** [comment]
hello! The issue is that the data in Wikidata for Q727911 is contradictory: it has 2 [`P31`](https://www.wikidata.org/wiki/Property:P31) values, one that gives the idea that it is of type series (*comic book series* [`Q14406742`](https://www.wikidata.org/wiki/Q14406742)), thus its appearance in the series value suggestions, and one that hints that its just a work (*comic book* [`Q1760610`](https://www.wikidata.org/wiki/Q1760610)), which is considered a different level in the [current data model](https://inventaire.github.io/entities-map/).

The way to solve this kind of issue (that unfortunately happen quite often):
* open each editions associated with the [serie currently considered a work](https://www.wikidata.org/wiki/Q727911) in new tabs
* remove the P31 value that gives the false idea it's as simple work (Q1760610) from [`Q727911`](https://www.wikidata.org/wiki/Q727911) (which should be done on Wikidata)
* in Inventaire, use the refresh button (near the edit pencil) to get the updated data, and create the missing serie parts to which the editions should be associated via the *edition of* ([`P629`](https://www.wikidata.org/entity/P629)) property

Would you like to give it a shot or would you prefer that I do it?

**Comment by pdesgarets** [comment]
I will give it a try, thanks
