### ISSUE TITLE
What source will you get French (non-english) data from ?

### ISSUE THREAD

**Issue by vindarel** [inventaire/inventaire#38]
Hey,
Well, first of all, congrats, it's a beautiful project, and I'm jealous because I was dreaming about doing it myself :p 

So, I tried it, and I don't find french results (searching by keywords). How do you plan to fetch french books (or generally non-english ones ?) ? (Connection to the BNF ? (in that case we must wait a bit before to have new titles)) However, when I search by isbn I seem to have results, but… later (that's another issue).
 Is the connection with OCLC (didn't quite understand what it is) supposed to fix that need ?
 (that's also a request for high level docs !)

**Comment by maxlath** [comment]
don't be jealous, jump in! [new contributors](https://github.com/inventaire/inventaire/wiki#new-contributors) are very welcome!! :D
I started a [high level documentation](https://github.com/inventaire/inventaire/wiki#high-level-documentation) section in the wiki in which i tried to answer the [data provenance question in the wiki](https://github.com/inventaire/inventaire/wiki/data), let me know if it is answers your question.
For what is of the OCLC, the connection is interesting for two reasons: data on books, and books availability in libraries to display in books results once we get geolocation \o/

**Comment by vindarel** [comment]
thanks, it explains the english-centric results. Still, my isbn searches weren't very succesfull.

**Comment by maxlath** [comment]
We are finally getting some high level documentation thank to our wiki! On this issues subject, see the [Books data](https://wiki.inventaire.io/wiki/Books-data) article.
After the large rework of works and editions data system during 2016, results should now be less English centric :)
I'm now closing this issue, but feel welcome to re-open it if you still struggle to find the expected results in your ISBN searches

**Comment by vindarel** [comment]
Ok, thanks for the doc. As a reminder (we quickly discussed this somewhere else), I wrote a python lib to find french (and spanish and german) books by isbn or full search, by scraping existing websites: https://gitlab.com/vindarel/bookshops It works well so far. I can imagine Inventaire running it and getting back the results as json, or doing its own scraping (in which case we could still work something together).

**Comment by maxlath** [comment]
> we quickly discussed this somewhere else

here: https://gitlab.com/mirelsol/alessandria/issues/52

Yes, we are kind of doing the same thing, but not being very comfortable with it, it is the one blackboxed/close-source thing, [requested by the server by HTTP when needed](https://github.com/inventaire/inventaire/blob/20c33591b4377d6903125aed184ab9fc00561393/server/data/dataseed/dataseed.coffee).

You can access its results per ISBN like so: https://inventaire.io/api/data?action=isbn&isbn=9788870028393
And the wikidata/inventaire style formatted version: https://inventaire.io/api/entities?action=by-uris&uris=isbn:9788870028393

But if I remember correctly, you need the prices, which isn't a concern in inventaire for now, especially as it would require to be handled in an international-friendly way, that is, not relying on the French unique price system: if and when it will come to inventaire, prices will probably come from the sellers themselves, rather than a centralized unique price.
