### ISSUE TITLE
replace reportPossibleDuplicate email tickets by a task document in database

### ISSUE THREAD

**Issue by maxlath** [inventaire/inventaire#410]
example: currently, [when a "possible work duplicate" is identified, an email is sent to admins](https://github.com/inventaire/inventaire-client/blob/9d4f8e7/app/modules/entities/views/editor/lib/create_edition_entity_from_work.coffee#L47-L49)

This means that only the admins get the info, and, due to the email setup, an admin wouldn't know if an other admin already had a look at the issue.

This could process could be improved by storing this kind of ticket in the database instead of only sending emails. I guess that could be a type of [task](https://github.com/inventaire/inventaire/blob/4303efa/server/models/task.js), but we would need to decouple tasks from their current unique use-case to a more flexible model, to make it re-usable for a more divers kind of case while keeping what makes a task a task, namely that it needs the attention of an admin or expert user, and that it has resolutions states.

If we were to go that way, maybe those tasks could be scoped to entities data, but that could also be a useful pattern for other non-entities-related administration tasks (ex: user reports)

**Comment by exilexi** [comment]
Yes! I'm not an admin but I am a wikidata enthusiast, I'd be happy to sort out these tickets, and I'm sure other non-admins would too.

**Comment by maxlath** [comment]
related issue: #91

**Comment by jum-s** [comment]
>   what makes a task a task, namely that it needs the attention of an admin or expert user

Today what inventaire consider to be a task is *only* a reconciliation between two authors suspected to represent the same person. A `task` has a `suspectUri` and a `suggestionUri` at its concept. For the issue's usecase, maybe we don't even need to change the task document much, as it is also a reconciliation between 2 entities.

I dont see any reason to includes any kind scoring attributes, which would probably mean some model validations to tweak to accept a task as only a type, a suspect and a suggestion. 

I also dont see any reason to store which user have reported the issue since its an automated report which is sent to admins. If necessary server logs are always around.

**Comment by jum-s** [comment]
as [the number of edition with more than one work](https://query.inventaire.io/#%23Editions%20without%20work%0ASELECT%20%28COUNT%28DISTINCT%20%3Fedition%29%20AS%20%3Fcount%29%20WHERE%20%7B%0A%20%20%3Fedition%20wdt%3AP31%20wd%3AQ3331189%20.%0A%20%20%3Fedition%20wdt%3AP629%20%3Fwork%20.%0A%20%20%3Fedition%20wdt%3AP629%20%3Fwork2%20.%0A%20%20FILTER%20%28STR%28%3Fwork%29%20%3E%20STR%28%3Fwork2%29%29%0A%7D) is low (~=500 or 0.12% of the total number of edition), creating several tasks (one task per edition's work) is acceptable. If that specific use case happens (several tasks created because the edition have several works), then the wrong tasks can be dismissed. Some hook already ensure that all tasks with the same suspect are dismissed when one of them is treated (merge its suspect).

**Comment by maxlath** [comment]
sounds acceptable

**Comment by jum-s** [comment]
done with 9e27b246
