### ISSUE TITLE
goodreads import failure when missing ISBN

### ISSUE THREAD

**Issue by Aethelflaed** [inventaire/inventaire#435]
I tried to import my goodreads collection and it fails without displaying anything, i.e. it feels like I have to submit the form but there's not button for that and no indication that anything has gone wrong.

The browser console does display a warning:

> Missing translation for key: "can't access property "replace", e is undefined" ( i18n.coffee:19:12)

I tried a file with only one entry, [goodreads-simple.log](https://github.com/inventaire/inventaire/files/5347340/goodreads-simple.log), which I had to rename as `.log` to upload it here, but the problem remains.

I enabled debug and tried again, and I can see that the CSV is correctly parsed, and directly after that is the i18n warning message, followed by:

> ===== alertbox: failed to find single target =====
> [err passed to catchAlert]

I tried one last test, with a book with an ISBN, and the import worked (i.e. I had the "2/ Select the books you want to add" part)

I don't know if inventaire requires an ISBN anyway, so this final behaviour is maybe not a problem, but the issue with reporting something to the user persists.

I'm available to provide more information if needed, and I'll try to find the time to look around the source code myself, but I'm not familiar with the toolset.

Great project anyway, I hope I manage to bring all my book-tracking on it ;-)

**Comment by maxlath** [comment]
hi @Aethelflaed

I found what looks like the corresponding error report in the server logs:

```
{
  statusCode: 500,
  labels: 'client error report',
  referer: 'https://inventaire.io/add/import',
}
Context: { message: `can't access property "replace", e is undefined` }
-----
[
  `can't access property "replace", e is undefined`,
  'r@https://inventaire.io/public/js/app.935219e.js:2:8230',
  's@https://inventaire.io/public/js/app.935219e.js:17:5147',
  'a@https://inventaire.io/public/js/app.935219e.js:17:5005',
  'addNewCandidates@https://inventaire.io/public/js/app.935219e.js:17:4684',
  ''
]
```
browsing stack traces in minified code isn't exactly a delight, but when looking at [https://inventaire.io/public/js/app.935219e.js:2:8230](https://inventaire.io/public/js/app.935219e.js), it seems that the problem was coming from 
[`normalizeIsbn`](https://github.com/inventaire/inventaire-client/blob/decaffeinate/app/lib/isbn.js#L5) being called with something that isn't a string (probably undefined) by [`getUri`](https://github.com/inventaire/inventaire-client/blob/331147e3be4469e56203389a5081c9ac5bd5ceb1/app/modules/inventory/collections/candidates.coffee#L35), which makes sense as that `getUri` function doesn't check if it does have an isbn at hand. Making that check https://github.com/inventaire/inventaire-client/commit/9525ffa seems to fix the issue: I was able to import the test file you provided \o/ That patch is now online, can you confirm that it works for you?

The client code whole code base is in a process of modernization (branch: https://github.com/inventaire/inventaire-client/tree/decaffeinate issues: https://github.com/inventaire/inventaire-client/issues/200 https://github.com/inventaire/inventaire-client/issues/201), so I wouldn't recommend jumping in the code just now as you would have to learn new tools shortly ^^

**Comment by Aethelflaed** [comment]
Thanks for the reactivity, everything works fine ^.^

And thanks for the head's up on the modernization process, I'll wait a bit then :)
