### ISSUE TITLE
Link to book without user name reacts unexpected

### ISSUE THREAD

**Issue by frimelle** [inventaire/inventaire#49]
I wanted to see whether it was possible to link to a book without a username in the link. 
So first I tried it with only the Wikidata entity id in the link:
https://inventaire.io/inventory/wd:Q163297 
which brings me to a normal 404 page.
But including the title:
https://inventaire.io/inventory/wd:Q163297/The_Stranger
shows me the loading icon and finally the message"Something went wrong :("
Besides it being super-cool to link to the actual book, the two things should probably react the same.

**Comment by maxlath** [comment]
you weren't very far! you just need to change the `inventory` section - which is dedicated to users' instances of books - by `entity` - which is the place for entities data. And indeed, then you have the choice between:
* [https://inventaire.io/entity/wd:Q163297](https://inventaire.io/entity/wd:Q163297)
* [https://inventaire.io/entity/wd:Q163297/The_Stranger](https://inventaire.io/entity/wd:Q163297/The_Stranger)
* or actually any label, it's just an option let open to be more readable than an id [https://inventaire.io/entity/wd:Q163297/hello this is dog](https://inventaire.io/entity/wd:Q163297/hello this is dog)

Now, the difference in errors is due to how the [client-side inventory router](https://github.com/inventaire/inventaire-client/blob/master/app/modules/inventory/inventory.coffee) interprets those urls:
* `/inventory/wd:Q163297` is catched by `'inventory/:user(/)': 'showUserInventory'`, then neither the client nor the server can find a user with username `wd:Q163297` so it rightfully shows a 404
* `/inventory/wd:Q163297/The_Stranger` is catched by `'inventory/:user/:entity(/:title)(/)': 'itemShow'`,
which before even trying to find a user for this username tries to parse the entity uri: it tries to split `The_Stranger` on `:` to determine the uri prefix and id, and logically fails to do so: `prefix and id not found for: The_Stranger / undefined`

I let this issue open until I can fix this difference in error handling, which should just be testing the passed parameters before preceding, and showing a 404 if not happy with those: no username should

**Comment by maxlath** [comment]
this was fixed by https://github.com/inventaire/inventaire-client/commit/18b2f874106008d6b9fcd661aa2b3e4525c9fcd9
