### ISSUE TITLE
Typos, rephrasing and bugs about strings

### ISSUE THREAD

**Issue by Airon90** [inventaire/inventaire#53]
While translating the software into Italian I found some typos:
- [Here](https://www.transifex.com/inventaire/inventaire/translate/#it/emails/51642891) and [here](https://www.transifex.com/inventaire/inventaire/translate/#it/emails/51642892) there are two exlamation marks. You should delete one (!! → !)
- «[go to %{username}'s inventory to accept**s** the invitation](https://www.transifex.com/inventaire/inventaire/translate/#it/emails/51642898)» should be «go to %{username}'s inventory to accept the invitation»
- «[Follow Inventaire development**s**](https://www.transifex.com/inventaire/inventaire/translate/#it/emails/51642901)» should be «Follow Inventaire development»
- «[Think you can contribute to make Inventaire better? Get involved!!](https://www.transifex.com/inventaire/inventaire/translate/#it/emails/51642902)» should be «Do you think you can contribute and make Inventaire better? Get involved!»
- «[Next **functionalities** to be developed:](https://www.transifex.com/inventaire/inventaire/translate/#it/emails/51642904)» should be better «Next **features** to be developed:»

Please don't close this issue. I have to finish the Italian translation and maybe more keys need to be changed.

**Comment by maxlath** [comment]
Thanks @Airon90 for both translating and reporting the typos!
I got those fixed, if you spot new ones, please add them as a comment hereafter so that I can get a notification. And yes, I let you close this issue once you think you're done and the expected corrections were made :)

**Comment by frimelle** [comment]
Commenting to be updated about typos, too. :)

**Comment by Airon90** [comment]
«[%{actingUserUsername} invited you to join the group**e** %{groupName}!](https://www.transifex.com/inventaire/inventaire/translate/#it/emails/59636181)» should be «%{actingUserUsername} invited you to join the group %{groupName}!»

**Comment by maxlath** [comment]
the reason for email subjets like `[%{groupName}] your request to join the group has been validated!` is that as it's the email subject, you often can see just a subpart of it; thus placing the group name first (or in other places, the book's title) gives better chances for it to be seen and gives context to the email. This is actually directly borrowed from what websites like github are doing in their mail notifications:
`[inventaire] Typos, rephrasing and bugs about strings (#53)`

**Comment by Airon90** [comment]
Ok, thank you very much!
See now [this string](https://www.transifex.com/inventaire/inventaire/translate/#it/emails/59636189): in the first part the object is a user (%{username}) but in the second part the subject is "they". What do you think to substitute "they" with "the user" (and obviously  to add "s" to "want")?

**Comment by Airon90** [comment]
The URL in https://www.transifex.com/inventaire/inventaire/translate/#it/emails/59636190 cannot be localized

**Comment by Airon90** [comment]
«[[...] and lot happened since we went first online in February: [...]](https://www.transifex.com/inventaire/inventaire/translate/#it/emails/66344157)» Which is the year? 2015? 2014?

**Comment by Airon90** [comment]
Last but not least, it is unclear the meaning of these two keys: «[raw links](https://www.transifex.com/inventaire/inventaire/translate/#it/emails/51642899)» and «[Messaging](https://www.transifex.com/inventaire/inventaire/translate/#it/emails/51642908)»

This is the last comment by now. I wait for

**Comment by maxlath** [comment]
**they**
using "they" instead of "he" or "she" seem to be an acceptable way to stay neutral http://www.oxforddictionaries.com/words/he-or-she-versus-they but you're not the first to be confused by it, it would be great to have a English native speaker confirming it

**urls**
what about using the corresponding Wikipedia article in each languages?
https://en.wikipedia.org/wiki/Open_knowledge => https://it.wikipedia.org/wiki/Open_knowledge
https://en.wikipedia.org/wiki/Free_software => https://it.wikipedia.org/wiki/Software_libero

**February**
It's 2015. This string is part of the first news paragraph and will thus to be removed in the coming month: [I started an entry on news in the wiki to explain this mechanism](https://github.com/inventaire/inventaire/wiki/Internationalization#news). Let me know if this is clear enough and if you have preferences on how to be notified as translation contributors when a new news paragraph is ready for translation: would a Transifex announcement work for you?

**raw links** and **Messaging**
My apologies, both were removed and don't need a translation anymore (see c0a80dd).
For the story, `raw links` was the title of a list of links without the url modification made by the email delivery service for tracking purpose, which was made unnecessary now that I disabled tracking globally.

**Comment by Airon90** [comment]
Hi maxlath!

* ```they```: I'm the first one that wants to stay neutral on gender words. However I proposed to use ```the user``` (singular and neutral) instead of ```they``` (plural and neutral) :P
* ```urls```: Transifex doesn't allow me to use localized articles of Wikipedia because it recognizes that the URLs are different from the source.
* ```February```: at first glance I didn't understand what you meant. I'll read it later when I'm not in a hurry :)
* ```raw links``` and ```Messaging```: thank you very much!

Now I translated only email keys. How to translate server side software keys?
Thank you very much!

**Comment by maxlath** [comment]
oh, I see now! So, if the urls customization can't be done in Transifex, this can always be done through git: see the commit dafa53b. Then, git source files have priority over Transifex translations exports in the [`generate_lang_json`](https://github.com/inventaire/inventaire/blob/i18n/generate_lang_json.coffee) procedure.
(more precisely, it will generate the `langCurrent` in [this line of find_keys](https://github.com/inventaire/inventaire/blob/i18n/lib/find_keys.coffee#L14))

Then, for what is of the server side translations, that's here! https://www.transifex.com/inventaire/inventaire_live/language/it
Transifex splitted inventaire in two projects, due to difference in the way files were updated, but I'm discussing with a friend working there on how to merge back both projects.

**Comment by maxlath** [comment]
closing this issue, please re-open new dedicated issues if some are still relevant
