### ISSUE TITLE
Books can't be modified on the website

### ISSUE THREAD

**Issue by PetiPandaRou** [inventaire/inventaire#55]
I want to add the author of this book : https://inventaire.io/entity/isbn:9782213687001/Le_crime_%C3%A9tait_sign%C3%A9

But I don't find where I can do that.

**Comment by maxlath** [comment]
This is because most of the book's data found by ISBN happen to come from Google Books, which is neither contributive nor libre (cf the [wiki article on data](https://github.com/inventaire/inventaire/wiki/data) ). Ideally, we should move progressively toward only linked, libre, and contribute databases such as the "Wikidata for objects" mentioned at the end of the wiki article, which would solve this issue. This will take some time to get there but this will happen: this is a major aspect of the whole project :)

**Comment by maxlath** [comment]
related roadmap card: [restructure the database to allow more detailed data](https://trello.com/c/doDQZ987/99-restructure-the-database-to-allow-more-detailed-data)

**Comment by maxlath** [comment]
@PetiPandaRou it is now possible \o/
Authors should be added on the work page (not on a specific edition), so in your case:
* work page: https://inventaire.io/entity/inv:1917e3d856a752b75e275743310e207f
* work data editor: https://inventaire.io/entity/inv:1917e3d856a752b75e275743310e207f/edit

**Comment by maxlath** [comment]
@PetiPandaRou it is now possible \o/
Authors should be added on the work page (not on a specific edition), so in your case:
* work page: https://inventaire.io/entity/inv:1917e3d856a752b75e275743310e207f
* work data editor: https://inventaire.io/entity/inv:1917e3d856a752b75e275743310e207f/edit
