### ISSUE TITLE
cannot set location

### ISSUE THREAD

**Issue by fkooman** [inventaire/inventaire#57]
when denying giving your position to inventaire.io it gives up on allowing you to set your location manually, e.g. using a map or something.

Using Firefox 44.0 on Linux, with `privacy.trackingprotection.enabled` set to true and no additional addons/plugins to block ads.

**Comment by maxlath** [comment]
Indeed, the position picker currently doesn't work without an initial position, either provided by the browser geolocation or previously set. Two clues on solving this issue:
* initializing the map an arbitrary point, eventually just at the lowest zoom, with the whole world map visible
* [allow to pick position from geocoding instead of map marker](https://github.com/inventaire/inventaire-client/issues/54)

**Comment by mtbottle** [comment]
Where is this at now?

**Comment by maxlath** [comment]
@mtbottle glad you ask! ;)
So since 2ede0e7, after 10 secondes without returning a geolocation, the geolocation request times out and return a default location. That could be considered a fixed issue, unless you see someway to grab the event "the user refused to give her location" to replace the sometime confusing 10 secondes timeout mechanism

**Comment by maxlath** [comment]
so this was fixed, the remaining problem of initializing the map at an arbitrary point is tracked in the [geocoding issue](https://github.com/inventaire/inventaire-client/issues/54)
