### ISSUE TITLE
Title difference between an edition and a book

### ISSUE THREAD

**Issue by thewholelifetolearn** [inventaire/inventaire#88]
Hi everyone,

I use Inventaire.io since some days now and I had a hard moment to understand why there could be 2 different titles between my exemplar and the book. I understood only yesterday night that I had an examplar of an edition of a book. But still, it is confusing to have two titles for the same "original" book.

I think the title must be common between the edition and the book. Indeed, the only properties that changes should be the editor, the publish date and the number of pages.

For example, in the case of the first volume of Harry Potter (https://inventaire.io/entity/wd:Q43361), there is one book with a title, an author, etc ... but there are different editions (hard covered, pocket, ...). Those editions have the same title and author.
A second example is the the fourth volume of the comic "Ekhö Monde Miroir" (https://inventaire.io/entity/inv:6ac43605017a51a83335f05735847cf5). There is one coloured edition and one black and white. But between those two, the title doesn't change.

**Comment by maxlath** [comment]
hello @thewholelifetolearn!
Unfortunately, this is part of the difficulties to modelize books data: a single work may have different titles depending on the edition. For instance, [*The Design of Everyday Things* had for first title *The Psychology of Everyday Things*](https://en.wikipedia.org/wiki/The_Design_of_Everyday_Things) ([see on inventaire.io](https://inventaire.io/entity/wd:Q7729821)). Thus, we can't really do otherwise than offering the option to set different [edition titles (`wdt:P1476`)](https://inventaire.io/api/entities?action=by-uris&uris=isbn:9780465067091) and [work `labels`](https://inventaire.io/api/entities?action=by-uris&uris=wd:Q7729821)

**Comment by thewholelifetolearn** [comment]
Perhaps, just add a checkbox near the title that when it is checked, the work title is also updated.

**Comment by maxlath** [comment]
oh that could be nice, see #61 for previous discussions on a Docker setup

**Comment by maxlath** [comment]
working on keeping work labels from a given language in sync with that language editions titles (05718e2) when there is a consensus among those (e4181b1)

**Comment by maxlath** [comment]
thus, when a work has a single edition, the way to updated both is to edit the edition title

**Comment by thewholelifetolearn** [comment]
I tried to edit a title of an edition and it updated the book too. It works well and i find it more practical now. 👍

**Comment by thewholelifetolearn** [comment]
I consider the issue as resolved with your proposal
