### ISSUE TITLE
Add a series ordinal property

### ISSUE THREAD

**Issue by thewholelifetolearn** [inventaire/inventaire#89]
There are many books like novels, comics, mangas that are part of a serie.  
It would be great to have a notion of volume or ordinal in wikidata vocabulary. That would ease the display of a book's title. It could be displayed like ``{{ serie title }} - Vol. {{ ordinal}} - {{ book title }}``.

I like very much such a display because it is very easy to know witch volume is missing in your library.

**Comment by maxlath** [comment]
yes! so that would be [`wdt:P1545`](https://www.wikidata.org/wiki/Property:P1545) right?

**Comment by thewholelifetolearn** [comment]
Yes. It seems to be it.

I don't have any knowledge in coffeescript but I would like to try to implement it. I hope to have some time in the next days

**Comment by maxlath** [comment]
Cool :D

First, if you are interested in learning a language to contribute to this project, and are not familiar with coffeescript and javascript, start by [learning javascript](https://github.com/nodeschool/lyon/blob/master/learnjavascript.md) as coffeescript is just javascript with an alternative syntax, but all the logic is the same, and you got to understand javascript to really master coffeescript. Plus, this project might soon [move to normal javascript](https://github.com/inventaire/inventaire/issues/72), so starting by learning javascript is definitely the best bet ;)

The difficulty with [`wdt:P1545`](https://www.wikidata.org/wiki/Property:P1545) is that it's datatype is `string` and not `number` to be able to accept values such as `2A` and alikes; but that's Wikidata's communities' choice, and inventaire is built with the idea to give higher data constraints to lower the bar for non-expert contributors. That's for the context, but actually, I think that keeping this flexibility in the datatype is a good thing. A possible battle plan:

### server-side
* add `wdt:P1545` to [the list of properties](https://github.com/inventaire/inventaire/blob/20c33591b4377d6903125aed184ab9fc00561393/server/controllers/entities/lib/properties.coffee) (I would guess with `stringBase`)

### client-side
* add `wdt:P1545` to the [work properties](https://github.com/inventaire/inventaire-client/blob/28d5637bddca29b1a5bef1d7bfda55c38e406690/app/lib/shared/properties_per_type.coffee) (NB: this module, as all in the `app/lib/shared` folder, are also used by the server)
* set `wdt:P1545` [editor parameters](https://github.com/inventaire/inventaire-client/blob/28d5637bddca29b1a5bef1d7bfda55c38e406690/app/modules/entities/lib/properties.coffee): we could start by re-using the existing `positive-integer` datatype editor, before creating a custom editor for those special cases (`2A`, [negative ranks](https://fr.wikipedia.org/wiki/Donjon_Potron-Minet), etc) later

**Comment by thewholelifetolearn** [comment]
I have some knowledge in Javascript. I have already programmed in that language but I'm no specialist. I'm more familiar with PHP, C and C++. I have done some Javascript for some frontend but no big things. I mostly used existing libraries that fulfilled my needs.

I will try to do those modifications soon but I must first create a working dev environment.

**Comment by maxlath** [comment]
If you happen to be on Ubuntu, it should be quite straight forward to setup a working dev environment following the [installation guide](https://github.com/inventaire/inventaire#installation)

**Comment by thewholelifetolearn** [comment]
Yes, I'm on Ubuntu. But I would like to install it through Docker so that I don't "pollute" my every day environment.

**Comment by maxlath** [comment]
I have started implementing it
server: 90930d4
client: [`b0eacac`](https://github.com/inventaire/inventaire-client/commit/b0eacac86ca758823d5294a32dc04ef462b5ede4)

[can be seen at work here](https://inventaire.io/entity/wd:Q1758672)

remaining to do:
* displaying the number on items
  * requires having the entities `wdt:P1545` integrated to [items snapshot data](https://github.com/inventaire/inventaire/blob/90930d4cab7545390c364fc4543ae69813a4b268/server/controllers/items/lib/snapshot/build_snapshot.coffee)

ideas of enhancement:
* let a user re-order a whole series by drag-and-drop, instead of having to edit every single work entity

**Comment by thewholelifetolearn** [comment]
Thanks a lot. I would have liked to do myself but I have few leisure time at the moment. 
Your enhancement idea is very good.  This possibility could be added on the series page.

I'm sorry but I didn't understand  the point on snapshots. What are they for?  
I looked a bit in the code and I didn't find documentation on the structure of the code or the elements (where is the work definition file? the edition definition file?). I'm used too a MVC kind structure that I don't gather here.

**Comment by maxlath** [comment]
@thewholelifetolearn sorry, I realized you offered to work on it only once I came back to this issue to announce the progresses :s 

snapshots are data inferred from other models a model keep at hand for convenience. For example, [an item will keep some data from its associated entity at hand](https://inventaire.io/api/items?action=by-ids&ids=278bbf4d704ee3c8d587fd73a885cca3): `authors`, `title`, `lang`, `series`, etc. It makes generating basic views about the item (either server side in emails or client side) simpler/cheaper by not having to make extra requests to all the [graph of the associated entities](https://inventaire.github.io/entities-map/) (an edition, its work, its authors, its series, etc).

So here the idea is to also have the series ordinal in items snapshot so that we can display rich titles as you suggested in your initial commentary. That shouldn't be much to do but it's indeed under-documented - my apologies - and possibly slightly hacky: I will do it if you don't mind.

Would you like to be attributed the [drag-and-drop reordering feature](https://github.com/inventaire/inventaire-client/issues/103)?

**Comment by maxlath** [comment]
considered done
