### ISSUE TITLE
Duplicates of manga series

### ISSUE THREAD

**Issue by thewholelifetolearn** [inventaire/inventaire#92]
Hi!

I'm trying to enter the most information possible at each work and book that I have in my library. Doing that, I encountered that seems to exists duplicates of a manga serie: Bakuman.

![capture du 2017-05-20 12-56-39](https://cloud.githubusercontent.com/assets/823564/26275248/a75c9304-3d5c-11e7-8fa4-eb2baa5bbb74.png)

Could it be possible to merge them? It seems to be that the correct manga serie is the last one on the screenshot (https://inventaire.io/entity/wd:Q11327594). I don't know what the others reference.

**Comment by maxlath** [comment]
ouch. what I think appened:
* I mistakenly created the [Q29982260](https://wikidata.org/entity/Q29982260) entity on Wikidata
* I started to use it on inventaire - which made it be referenced by our [search engine](https://github.com/inventaire/wikidata-subset-search-engine)
* Seeing that another entity - [Q11327594](https://www.wikidata.org/wiki/Q11327594) - existed, I merged it in Wikidata, but the search engine didn't got this information, so it still returns it in search results

This issue is this part of a larger problem: how to keep in sync with entities changes happening on Wikidata. I started working on it by [requesting the search engine to refresh its data](https://github.com/inventaire/inventaire/blob/add48388a9ebdb3b17103179f97b73870008567d/server/controllers/entities/lib/update_wikidata_subset_search_engine.coffee) every times the inventaire server requests entities data to Wikidata (that is, either if the entity is unknown yet, or the cached data is too old, or if the client requested refreshed data). But we might need something more radical: we could directly [listen to Wikidata change feed](https://www.wikidata.org/w/api.php?action=query&list=recentchanges&format=json), filter to keep only entities that are already referenced, and update those.

**Comment by thewholelifetolearn** [comment]
There is similar issue with authors

![image](https://cloud.githubusercontent.com/assets/823564/26311618/3e61638e-3f05-11e7-898e-2584add6d956.png)

`Christophe Arleston` comes up in the list at least 10 times! I don't know which one to choose.

**Comment by maxlath** [comment]
Those should be merged, which is an admin task. The workflow to get it done progressively is under development #91 

The rule of thumb is to always prefer the Wikidata entity (the ones with a `Q123`-like id) when one is available as all the others will be merged into it, but it's ok to pick any - if there is no doubt they are duplicates - as all the links will be redirected when merged.

**Comment by maxlath** [comment]
ok so coming back on this issue, there are two things:
- the issue of updating the search engine, which should now be solved by https://github.com/inventaire/wikidata-subset-search-engine/commit/229e215
- the issue of duplicated entities which is tracked by #129  and addressed by #131
